<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Delete, Download, Refresh, Search, Upload, View } from '@element-plus/icons-vue'
import api from '../api/client.js'
const rows=ref([]),categories=ref([]),keyword=ref(''),categoryFilter=ref(''),uploadVisible=ref(false),categoryId=ref(''),files=ref([]),busy=ref(false),previewVisible=ref(false),preview=ref(null)
const filtered=computed(()=>rows.value.filter(row=>(!keyword.value||row.name.toLowerCase().includes(keyword.value.toLowerCase()))&&(!categoryFilter.value||String(row.category_id)===String(categoryFilter.value))))
async function load(){const [d,c]=await Promise.all([api.get('/documents'),api.get('/categories')]);rows.value=d.data.data;categories.value=c.data.data}
function choose(file){files.value=[file.raw]}
async function upload(){if(!files.value.length)return;busy.value=true;try{for(const file of files.value){const body=new FormData();body.append('file',file);if(categoryId.value)body.append('category_id',categoryId.value);await api.post('/documents',body)}ElMessage.success('文档已解析、切片并建立索引');uploadVisible.value=false;files.value=[];await load()}finally{busy.value=false}}
async function remove(row){await ElMessageBox.confirm(`删除“${row.name}”及全部知识切片？`,'删除文档',{type:'warning'});await api.delete(`/documents/${row.id}`);ElMessage.success('已删除');await load()}
async function view(row){preview.value=(await api.get(`/documents/${row.id}`)).data.data;previewVisible.value=true}
async function download(row){const res=await api.get(`/documents/${row.id}/download`,{responseType:'blob'});const url=URL.createObjectURL(res.data);const a=document.createElement('a');a.href=url;a.download=row.original_name;a.click();URL.revokeObjectURL(url)}
function size(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`}
onMounted(load)
</script>
<template><section class="page-wrap"><div class="page-head"><div><h2>企业知识库</h2><p>统一管理企业资料，上传后自动完成解析、切片、索引并进入内部问答。</p></div><el-button type="primary" :icon="Upload" @click="uploadVisible=true">上传文档</el-button></div>
<div class="panel"><div class="panel-head toolbar"><el-input v-model="keyword" :prefix-icon="Search" placeholder="搜索文档名称" style="width:260px" clearable/><el-select v-model="categoryFilter" placeholder="全部分类" clearable style="width:180px"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select><span class="grow"></span><el-button :icon="Refresh" @click="load">刷新</el-button></div>
<el-table :data="filtered"><el-table-column prop="name" label="文档名称" min-width="250"/><el-table-column label="知识分类" min-width="150"><template #default="{row}">{{row.category?.name||'未分类'}}</template></el-table-column><el-table-column label="文件大小" width="120"><template #default="{row}">{{size(row.size_bytes)}}</template></el-table-column><el-table-column prop="chunks_count" label="知识切片" width="110"/><el-table-column label="索引状态" width="130"><template #default="{row}"><el-tag :type="row.status==='indexed'?'success':row.status==='failed'?'danger':'warning'">{{row.status==='indexed'?'已索引':row.status==='failed'?'失败':'处理中'}}</el-tag></template></el-table-column><el-table-column label="更新时间" width="190"><template #default="{row}">{{new Date(row.updated_at).toLocaleString()}}</template></el-table-column><el-table-column label="操作" width="210"><template #default="{row}"><el-button link :icon="View" @click="view(row)">查看</el-button><el-button link :icon="Download" @click="download(row)">下载</el-button><el-button link type="danger" :icon="Delete" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div v-if="!filtered.length" class="empty-state">暂无符合条件的知识文档</div></div>
<el-dialog v-model="uploadVisible" title="上传知识文档" width="600"><el-form label-position="top"><el-form-item label="知识分类"><el-select v-model="categoryId" placeholder="请选择分类，可不选" clearable style="width:100%"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select></el-form-item><el-form-item label="选择文件"><el-upload drag :auto-upload="false" :limit="1" accept=".txt,.md,.markdown,.log,.csv,.json,.docx,.xlsx,.pdf" :on-change="choose" :on-remove="()=>files=[]"><el-icon size="38"><Upload/></el-icon><div>拖放文件到此处，或点击选择</div><template #tip>支持 TXT、Markdown、LOG、CSV、JSON、DOCX、XLSX 和可复制文字 PDF，单文件最大 10 MB</template></el-upload></el-form-item></el-form><template #footer><el-button @click="uploadVisible=false">取消</el-button><el-button type="primary" :loading="busy" :disabled="!files.length" @click="upload">上传并建立索引</el-button></template></el-dialog>
<el-drawer v-model="previewVisible" title="知识切片预览" size="55%"><template v-if="preview"><el-descriptions :column="2" border><el-descriptions-item label="文档">{{preview.name}}</el-descriptions-item><el-descriptions-item label="分类">{{preview.category?.name||'未分类'}}</el-descriptions-item><el-descriptions-item label="切片数">{{preview.chunks_count}}</el-descriptions-item><el-descriptions-item label="状态">{{preview.status}}</el-descriptions-item></el-descriptions><article v-for="chunk in preview.chunks" :key="chunk.id" class="citation-item"><strong>切片 {{chunk.sequence}}</strong><p style="line-height:1.8;white-space:pre-wrap">{{chunk.content}}</p></article></template></el-drawer></section></template>
