<script setup>
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import api from '../api/client.js'
const categories=ref([]),categoryId=ref(''),question=ref(''),answer=ref(''),citations=ref([]),asking=ref(false),messageId=ref('')
onMounted(async()=>{categories.value=(await api.get('/categories')).data.data})
async function ask(){if(!question.value.trim())return;asking.value=true;try{const res=await api.post('/knowledge-chat/ask',{question:question.value,category_id:categoryId.value||null});answer.value=res.data.answer;citations.value=res.data.citations||[];messageId.value=res.data.message_id}finally{asking.value=false}}
async function feedback(rating){if(!messageId.value)return;await api.post('/knowledge-chat/feedback',{message_id:messageId.value,rating});ElMessage.success('反馈已记录')}
</script>
<template><section class="page-wrap"><div class="page-head"><div><h2>内部知识问答</h2><p>答案只基于已上传的企业知识，并展示可核验的引用来源。</p></div></div><div class="chat-layout"><div class="panel"><div class="panel-body"><el-select v-model="categoryId" clearable placeholder="全部知识分类" style="width:220px;margin-bottom:12px"><el-option v-for="c in categories" :key="c.id" :label="c.name" :value="c.id"/></el-select><el-input v-model="question" type="textarea" :rows="4" placeholder="请输入企业内部问题" @keydown.ctrl.enter="ask"/><div style="display:flex;justify-content:space-between;align-items:center;margin-top:12px"><span style="color:#8a94a6;font-size:12px">Ctrl + Enter 快速提问</span><el-button type="primary" :loading="asking" @click="ask">开始检索并回答</el-button></div><div v-if="answer" class="answer-box" style="margin-top:18px">{{answer}}</div><div v-if="answer" style="margin-top:12px"><el-button size="small" @click="feedback('up')">回答有用</el-button><el-button size="small" @click="feedback('down')">需要改进</el-button></div></div></div><aside class="panel"><div class="panel-head"><h3>引用来源</h3><el-tag>{{citations.length}}</el-tag></div><div class="panel-body"><div v-for="c in citations" :key="c.chunk_id" class="citation-item"><strong>[{{c.number}}] {{c.document_name}}</strong><p style="color:#697386;line-height:1.6">{{c.excerpt}}</p><el-tag size="small" type="info">相关度 {{c.score}}</el-tag></div><div v-if="!citations.length" class="empty-state" style="padding:30px 5px">提问后在这里核验引用来源</div></div></aside></div></section></template>
