<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import api from '../api/client.js'
const rows=ref([]),visible=ref(false),editing=ref(null),saving=ref(false),form=reactive({name:'',webhook_url:'',enabled:true})
async function load(){rows.value=(await api.get('/wecom-configs')).data.data}
function open(row=null){editing.value=row;Object.assign(form,{name:row?.name||'',webhook_url:'',enabled:row?.enabled??true});visible.value=true}
async function save(){saving.value=true;try{const payload={name:form.name,enabled:form.enabled};if(form.webhook_url)payload.webhook_url=form.webhook_url;editing.value?await api.put(`/wecom-configs/${editing.value.id}`,payload):await api.post('/wecom-configs',payload);ElMessage.success('机器人配置已保存');visible.value=false;await load()}finally{saving.value=false}}
async function validate(row){const res=await api.post(`/wecom-configs/${row.id}/test`,{send_test_message:false});ElMessage.success(res.data.message)}
async function send(row){await ElMessageBox.confirm('将向对应企业微信群发送一条固定测试消息，是否继续？','发送测试消息',{type:'warning'});const res=await api.post(`/wecom-configs/${row.id}/test`,{send_test_message:true});ElMessage.success(res.data.message);await load()}
async function remove(row){await ElMessageBox.confirm(`确认删除机器人“${row.name}”？`,'删除配置',{type:'warning'});await api.delete(`/wecom-configs/${row.id}`);await load()}
onMounted(load)
</script>
<template><section class="page-wrap"><div class="page-head"><div><h2>企业微信机器人</h2><p>配置企业微信群机器人，用于知识库运行通知；不包含客户会话、AI客服或自动回复。</p></div><el-button type="primary" @click="open()">新增机器人</el-button></div>
<el-alert title="安全说明" description="Webhook 在服务端加密保存，页面和接口不返回明文；仅允许企业微信官方 qyapi.weixin.qq.com 地址。" type="info" show-icon :closable="false" style="margin-bottom:16px"/>
<div class="panel"><el-table :data="rows"><el-table-column prop="name" label="机器人名称" min-width="200"/><el-table-column label="Webhook" width="130"><template #default><el-tag type="success">已加密配置</el-tag></template></el-table-column><el-table-column label="启用状态" width="120"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'已启用':'已停用'}}</el-tag></template></el-table-column><el-table-column label="最近测试" min-width="220"><template #default="{row}"><span v-if="row.last_tested_at" :class="['status-dot',row.last_test_status==='success'?'':'error']"></span>{{row.last_test_message||'尚未测试'}}</template></el-table-column><el-table-column label="操作" width="300"><template #default="{row}"><el-button link type="primary" @click="validate(row)">校验地址</el-button><el-button link type="primary" @click="send(row)">发送测试</el-button><el-button link @click="open(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table><div v-if="!rows.length" class="empty-state">尚未配置企业微信机器人</div></div>
<el-dialog v-model="visible" :title="editing?'编辑企业微信机器人':'新增企业微信机器人'" width="600"><el-form label-position="top"><el-form-item label="机器人名称"><el-input v-model="form.name" placeholder="例如：知识库运维群"/></el-form-item><el-form-item :label="editing?'Webhook 地址（留空表示不修改）':'Webhook 地址'"><el-input v-model="form.webhook_url" type="password" show-password placeholder="https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=..."/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" :loading="saving" :disabled="!form.name||(!editing&&!form.webhook_url)" @click="save">保存</el-button></template></el-dialog></section></template>
